# Site settings
title: Archiverify
email: dev@dancorder.com
description: > # this means to ignore newlines until "baseurl:"
  Archiverify is an archive synchronisation and verification tool.
baseurl: "/Archiverify" # the subpath of your site, e.g. /blog/
url: "http://dancorder.github.io" # the base hostname & protocol for your site
twitter_username: DanCorder
github_username:  DanCorder

# Build settings
markdown: kramdown
